"""OpenClaw-specific SDK surfaces."""

from .gateway import (
    GatewayClient,
    GatewayError,
    GatewayNodePairingRequired,
    NodeServer,
    serve_node,
    ChatEvent,
    GatewayChatToolCall,
    GatewayChatMessageSummary,
    extract_gateway_chat_thinking,
    extract_gateway_chat_media_urls,
    extract_gateway_chat_tool_calls,
    normalize_gateway_chat_message,
)
from .node_proxy import (
    EGRESS_COMMANDS,
    EgressCommandHandlers,
    EgressNodeClient,
    EgressNodeServer,
    EgressPolicyError,
    EgressProtocolError,
    LoopbackNodeProxy,
    NodeEgressClient,
    NodeEgressCommandHandlers,
    NodeEgressServer,
)

__all__ = [
    "GatewayClient",
    "GatewayError",
    "GatewayNodePairingRequired",
    "NodeServer",
    "serve_node",
    "ChatEvent",
    "GatewayChatToolCall",
    "GatewayChatMessageSummary",
    "extract_gateway_chat_thinking",
    "extract_gateway_chat_media_urls",
    "extract_gateway_chat_tool_calls",
    "normalize_gateway_chat_message",
    "EGRESS_COMMANDS",
    "EgressCommandHandlers",
    "EgressNodeClient",
    "EgressNodeServer",
    "EgressPolicyError",
    "EgressProtocolError",
    "LoopbackNodeProxy",
    "NodeEgressClient",
    "NodeEgressCommandHandlers",
    "NodeEgressServer",
]
