"""HyperCLI SDK - Python client for HyperCLI API"""
from ._compat import ensure_collections_compat

ensure_collections_compat()

from .client import HyperCLI
from .config import (
    configure,
    GHCR_IMAGES,
    COMFYUI_IMAGE,
    DEFAULT_API_URL,
    DEFAULT_WS_URL,
    DEFAULT_AGENTS_API_BASE_URL,
    DEFAULT_AGENTS_WS_URL,
    DEV_AGENTS_API_BASE_URL,
    DEV_AGENTS_WS_URL,
    get_api_key,
    get_agent_api_key,
    get_api_url,
    get_ws_url,
    get_agents_api_base_url,
    get_agents_ws_url,
)
from .http import APIError, AsyncHTTPClient
from .instances import GPUType, GPUConfig, Region, GPUPricing, PricingTier
from .jobs import (
    Job,
    JobListPage,
    JobMetrics,
    GPUMetrics,
    find_job,
    find_by_id,
    find_by_hostname,
    find_by_ip,
    get_job_tags,
    job_has_tags,
    normalize_job_tags,
)
from .renders import Render, RenderStatus
from .voice import VoiceAPI
from .voice_stream import VoiceChunk, VoiceSession, VoiceStreamError
from .models import Model, ModelsAPI
from .workspaces import (
    DownloadUrl,
    Workspace,
    WorkspaceAccessEntry,
    WorkspaceAccessSnapshot,
    WorkspaceAccessVisibility,
    WorkspaceAgentAssociation,
    WorkspaceFile,
    WorkspaceGrant,
    WorkspaceManifest,
    WorkspacesAPI,
)
from .x402 import X402Client, X402JobLaunch, X402FlowCreate, X402RenderCreate, FlowCatalogItem
from .files import File, AsyncFiles
from .user import AuthMe, RuntimeIdentity, User, UserAPI
from .job import BaseJob, ComfyUIJob, GradioJob, apply_params, apply_graph_modes, find_node, find_nodes, load_template, graph_to_api, expand_subgraphs, DEFAULT_OBJECT_INFO
from .logs import LogStream, stream_logs, fetch_logs
from .agents import (
    Agent,
    AgentCapacity,
    AgentFileSource,
    AgentRouteConfig,
    AgentRoutes,
    AgentSlot,
    AgentSlotInventory,
    BuzzAgent,
    BuzzLaunchConfig,
    ClaudeCodeAgent,
    CodingAgent,
    CodexAgent,
    DEFAULT_AGENT_RUNTIME_SCOPES,
    DEFAULT_BUZZ_AGENT_IMAGE,
    DEFAULT_BUZZ_CODING_AGENT_IMAGES,
    DEFAULT_CODING_AGENT_IMAGES,
    DEFAULT_CODING_AGENT_SYNC_INCLUDES,
    DeploymentEvent,
    Deployments,
    ExecResult,
    GooseAgent,
    KimiCodeAgent,
    OpenClawAgent,
    OpenClawFileSource,
    OpenClawProAgent,
    OpenCodeAgent,
    RuntimeAuthClient,
    RuntimeAuthMethod,
    RuntimeAuthStatus,
    RuntimeLoginSession,
    build_agent_config,
    build_browser_desktop_url,
    build_openclaw_memory_index_env,
    build_openclaw_routes,
    build_openclaw_workspaces_sync_env,
)
from .shell import ShellSession, shell_connect
from .agent import (
    HyperAgent,
    HyperAgentCanonicalPlanId,
    HyperAgentPlan,
    HyperAgentCurrentPlan,
    HyperAgentEntitlements,
    HyperAgentEntitlementsSummary,
    HyperAgentSubscription,
    HyperAgentSubscriptionMutationResult,
    HyperAgentSubscriptionSummary,
    HyperAgentModel,
    HyperAgentUsageSummary,
    HyperAgentUsageHistoryEntry,
    HyperAgentUsageHistory,
    HyperAgentKeyUsageEntry,
    HyperAgentKeyUsage,
    HyperAgentTypePreset,
    HyperAgentTypePlan,
    HyperAgentTypeCatalog,
    HyperAgentBillingProfileFields,
    HyperAgentBillingInfo,
    HyperAgentBillingProfileResponse,
    HyperAgentBillingUser,
    HyperAgentPaymentSubscription,
    HyperAgentPaymentEntitlement,
    HyperAgentPayment,
    HyperAgentPaymentsResponse,
    HyperAgentStripeCheckoutResponse,
    HyperAgentX402CheckoutResponse,
    parse_hyper_agent_plan_id,
)
from .gateway import (
    GatewayClient,
    GatewayError,
    ChatEvent,
    GatewayChatToolCall,
    GatewayChatMessageSummary,
    extract_gateway_chat_thinking,
    extract_gateway_chat_media_urls,
    extract_gateway_chat_tool_calls,
    normalize_gateway_chat_message,
)
__version__ = "2026.6.26"
__all__ = [
    "HyperCLI",
    "configure",
    "get_api_key",
    "get_agent_api_key",
    "get_api_url",
    "get_ws_url",
    "get_agents_api_base_url",
    "get_agents_ws_url",
    "APIError",
    # Images
    "GHCR_IMAGES",
    "COMFYUI_IMAGE",
    "DEFAULT_API_URL",
    "DEFAULT_WS_URL",
    "DEFAULT_AGENTS_API_BASE_URL",
    "DEFAULT_AGENTS_WS_URL",
    "DEV_AGENTS_API_BASE_URL",
    "DEV_AGENTS_WS_URL",
    # Instance types
    "GPUType",
    "GPUConfig",
    "Region",
    "GPUPricing",
    "PricingTier",
    # Jobs API
    "Job",
    "JobListPage",
    "JobMetrics",
    "GPUMetrics",
    "normalize_job_tags",
    "get_job_tags",
    "job_has_tags",
    # Renders API
    "Render",
    "RenderStatus",
    "VoiceAPI",
    "VoiceChunk",
    "VoiceSession",
    "VoiceStreamError",
    "Model",
    "ModelsAPI",
    "DownloadUrl",
    "Workspace",
    "WorkspaceAccessEntry",
    "WorkspaceAccessSnapshot",
    "WorkspaceAccessVisibility",
    "WorkspaceAgentAssociation",
    "WorkspaceFile",
    "WorkspaceGrant",
    "WorkspaceManifest",
    "WorkspacesAPI",
    # x402 API
    "X402Client",
    "X402JobLaunch",
    "X402FlowCreate",
    "X402RenderCreate",
    "FlowCatalogItem",
    # Files API
    "File",
    "AsyncFiles",
    "User",
    "UserAPI",
    "AuthMe",
    "RuntimeIdentity",
    "AsyncHTTPClient",
    # Job lookup utils
    "find_job",
    "find_by_id",
    "find_by_hostname",
    "find_by_ip",
    # Job helpers
    "BaseJob",
    "ComfyUIJob",
    "GradioJob",
    # Workflow utils
    "apply_params",
    "apply_graph_modes",
    "find_node",
    "find_nodes",
    "load_template",
    "graph_to_api",
    "expand_subgraphs",
    "DEFAULT_OBJECT_INFO",
    # Log streaming
    "LogStream",
    "stream_logs",
    "fetch_logs",
    # Agents (Reef Pods)
    "Deployments",
    "DeploymentEvent",
    "Agent",
    "AgentCapacity",
    "AgentFileSource",
    "AgentRouteConfig",
    "AgentRoutes",
    "AgentSlot",
    "AgentSlotInventory",
    "BuzzAgent",
    "BuzzLaunchConfig",
    "CodingAgent",
    "DEFAULT_AGENT_RUNTIME_SCOPES",
    "DEFAULT_BUZZ_AGENT_IMAGE",
    "DEFAULT_CODING_AGENT_IMAGES",
    "DEFAULT_CODING_AGENT_SYNC_INCLUDES",
    "DEFAULT_BUZZ_CODING_AGENT_IMAGES",
    "OpenCodeAgent",
    "CodexAgent",
    "ClaudeCodeAgent",
    "GooseAgent",
    "KimiCodeAgent",
    "OpenClawAgent",
    "OpenClawFileSource",
    "OpenClawProAgent",
    "RuntimeAuthClient",
    "RuntimeAuthMethod",
    "RuntimeAuthStatus",
    "RuntimeLoginSession",
    "ExecResult",
    "build_agent_config",
    "build_browser_desktop_url",
    "build_openclaw_routes",
    "build_openclaw_memory_index_env",
    "build_openclaw_workspaces_sync_env",
    # Shell
    "ShellSession",
    "shell_connect",
    # HyperAgent
    "HyperAgent",
    "HyperAgentCanonicalPlanId",
    "HyperAgentPlan",
    "HyperAgentCurrentPlan",
    "HyperAgentEntitlements",
    "HyperAgentEntitlementsSummary",
    "HyperAgentSubscription",
    "HyperAgentSubscriptionMutationResult",
    "HyperAgentSubscriptionSummary",
    "HyperAgentModel",
    "HyperAgentUsageSummary",
    "HyperAgentUsageHistoryEntry",
    "HyperAgentUsageHistory",
    "HyperAgentKeyUsageEntry",
    "HyperAgentKeyUsage",
    "HyperAgentTypePreset",
    "HyperAgentTypePlan",
    "HyperAgentTypeCatalog",
    "HyperAgentBillingProfileFields",
    "HyperAgentBillingInfo",
    "HyperAgentBillingProfileResponse",
    "HyperAgentBillingUser",
    "HyperAgentPaymentSubscription",
    "HyperAgentPaymentEntitlement",
    "HyperAgentPayment",
    "HyperAgentPaymentsResponse",
    "HyperAgentStripeCheckoutResponse",
    "HyperAgentX402CheckoutResponse",
    "parse_hyper_agent_plan_id",
    # OpenClaw Gateway
    "GatewayClient",
    "GatewayError",
    "ChatEvent",
    "GatewayChatToolCall",
    "GatewayChatMessageSummary",
    "extract_gateway_chat_thinking",
    "extract_gateway_chat_media_urls",
    "extract_gateway_chat_tool_calls",
    "normalize_gateway_chat_message",
]
