import type { ComponentType, CSSProperties } from "react";
import {
  SiAnthropic,
  SiBrave,
  SiCloudflare,
  SiDeepgram,
  SiDiscord,
  SiDuckduckgo,
  SiElevenlabs,
  SiGithub,
  SiGithubcopilot,
  SiGoogle,
  SiGooglechat,
  SiHuggingface,
  SiImessage,
  SiLine,
  SiMatrix,
  SiMattermost,
  SiMistralai,
  SiNextcloud,
  SiNvidia,
  SiOllama,
  SiOpenai,
  SiPerplexity,
  SiSignal,
  SiSlack,
  SiTelegram,
  SiTwitch,
  SiVercel,
  SiWhatsapp,
  SiX,
  SiXiaomi,
  SiZalo,
} from "react-icons/si";

import { TeamsIcon } from "../BrandIcons";

export type IntegrationBrandIcon = ComponentType<{ className?: string; style?: CSSProperties }>;

const THEMED_BRAND_COLOR = "var(--foreground)";

export const INTEGRATION_BRAND_LOGOS: Record<string, { icon: IntegrationBrandIcon; color: string; foreground?: string }> = {
  anthropic: { icon: SiAnthropic, color: THEMED_BRAND_COLOR },
  brave: { icon: SiBrave, color: THEMED_BRAND_COLOR },
  "cloudflare-ai-gateway": { icon: SiCloudflare, color: THEMED_BRAND_COLOR },
  "copilot-proxy": { icon: SiGithubcopilot, color: THEMED_BRAND_COLOR },
  deepgram: { icon: SiDeepgram, color: THEMED_BRAND_COLOR },
  discord: { icon: SiDiscord, color: "var(--integration-discord)", foreground: "var(--integration-discord-foreground)" },
  duckduckgo: { icon: SiDuckduckgo, color: THEMED_BRAND_COLOR },
  elevenlabs: { icon: SiElevenlabs, color: THEMED_BRAND_COLOR },
  google: { icon: SiGoogle, color: THEMED_BRAND_COLOR },
  googlechat: { icon: SiGooglechat, color: THEMED_BRAND_COLOR },
  github: { icon: SiGithub, color: THEMED_BRAND_COLOR },
  "github-copilot": { icon: SiGithubcopilot, color: THEMED_BRAND_COLOR },
  huggingface: { icon: SiHuggingface, color: THEMED_BRAND_COLOR },
  imessage: { icon: SiImessage, color: THEMED_BRAND_COLOR },
  line: { icon: SiLine, color: THEMED_BRAND_COLOR },
  matrix: { icon: SiMatrix, color: THEMED_BRAND_COLOR },
  mattermost: { icon: SiMattermost, color: THEMED_BRAND_COLOR },
  mistral: { icon: SiMistralai, color: THEMED_BRAND_COLOR },
  msteams: { icon: TeamsIcon, color: THEMED_BRAND_COLOR },
  nextcloud: { icon: SiNextcloud, color: THEMED_BRAND_COLOR },
  "nextcloud-talk": { icon: SiNextcloud, color: THEMED_BRAND_COLOR },
  nvidia: { icon: SiNvidia, color: THEMED_BRAND_COLOR },
  ollama: { icon: SiOllama, color: THEMED_BRAND_COLOR },
  openai: { icon: SiOpenai, color: THEMED_BRAND_COLOR },
  perplexity: { icon: SiPerplexity, color: THEMED_BRAND_COLOR },
  signal: { icon: SiSignal, color: THEMED_BRAND_COLOR },
  slack: { icon: SiSlack, color: "var(--integration-slack)", foreground: "var(--integration-slack-foreground)" },
  telegram: { icon: SiTelegram, color: "var(--integration-telegram)", foreground: "var(--integration-telegram-foreground)" },
  twitch: { icon: SiTwitch, color: THEMED_BRAND_COLOR },
  "vercel-ai-gateway": { icon: SiVercel, color: THEMED_BRAND_COLOR },
  whatsapp: { icon: SiWhatsapp, color: "var(--integration-whatsapp)", foreground: "var(--integration-whatsapp-foreground)" },
  xai: { icon: SiX, color: THEMED_BRAND_COLOR },
  xiaomi: { icon: SiXiaomi, color: THEMED_BRAND_COLOR },
  zalo: { icon: SiZalo, color: THEMED_BRAND_COLOR },
  zalouser: { icon: SiZalo, color: THEMED_BRAND_COLOR },
};
