import type { ComponentType, CSSProperties } from "react";
import { Building2 } from "lucide-react";
import {
  SiAnthropic,
  SiAsana,
  SiBrave,
  SiCloudflare,
  SiDeepgram,
  SiDiscord,
  SiDuckduckgo,
  SiElevenlabs,
  SiGithub,
  SiGithubcopilot,
  SiGitlab,
  SiGmail,
  SiGoogle,
  SiGooglecalendar,
  SiGooglechat,
  SiGoogledrive,
  SiHuggingface,
  SiImessage,
  SiJira,
  SiLine,
  SiLinear,
  SiMatrix,
  SiMattermost,
  SiMistralai,
  SiNextcloud,
  SiNotion,
  SiNvidia,
  SiOllama,
  SiOpenai,
  SiPerplexity,
  SiSignal,
  SiSlack,
  SiTelegram,
  SiTrello,
  SiTwitch,
  SiVercel,
  SiWhatsapp,
  SiX,
  SiXiaomi,
  SiZalo,
} from "react-icons/si";

import { TeamsIcon } from "../BrandIcons";

export type IntegrationBrandIcon = ComponentType<{ className?: string; style?: CSSProperties }>;

export const INTEGRATION_BRAND_LOGOS: Record<string, { icon: IntegrationBrandIcon; color: string }> = {
  anthropic: { icon: SiAnthropic, color: "#d4c5b4" },
  asana: { icon: SiAsana, color: "#f06a6a" },
  brave: { icon: SiBrave, color: "#fb542b" },
  "cloudflare-ai-gateway": { icon: SiCloudflare, color: "#f38020" },
  "copilot-proxy": { icon: SiGithubcopilot, color: "#ffffff" },
  deepgram: { icon: SiDeepgram, color: "#13ef93" },
  discord: { icon: SiDiscord, color: "#5865f2" },
  duckduckgo: { icon: SiDuckduckgo, color: "#de5833" },
  elevenlabs: { icon: SiElevenlabs, color: "#ffffff" },
  gitlab: { icon: SiGitlab, color: "#fc6d26" },
  gmail: { icon: SiGmail, color: "#ea4335" },
  google: { icon: SiGoogle, color: "#4285f4" },
  googlechat: { icon: SiGooglechat, color: "#34a853" },
  "google-calendar": { icon: SiGooglecalendar, color: "#4285f4" },
  "google-drive": { icon: SiGoogledrive, color: "#34a853" },
  github: { icon: SiGithub, color: "#ffffff" },
  "github-copilot": { icon: SiGithubcopilot, color: "#ffffff" },
  hubspot: { icon: Building2, color: "#ff5c35" },
  huggingface: { icon: SiHuggingface, color: "#ffd21e" },
  imessage: { icon: SiImessage, color: "#34c759" },
  jira: { icon: SiJira, color: "#0c66e4" },
  line: { icon: SiLine, color: "#06c755" },
  linear: { icon: SiLinear, color: "#ffffff" },
  matrix: { icon: SiMatrix, color: "#ffffff" },
  mattermost: { icon: SiMattermost, color: "#1e325c" },
  mistral: { icon: SiMistralai, color: "#ff7000" },
  msteams: { icon: TeamsIcon, color: "#6264a7" },
  nextcloud: { icon: SiNextcloud, color: "#0082c9" },
  "nextcloud-talk": { icon: SiNextcloud, color: "#0082c9" },
  notion: { icon: SiNotion, color: "#ffffff" },
  nvidia: { icon: SiNvidia, color: "#76b900" },
  ollama: { icon: SiOllama, color: "#ffffff" },
  openai: { icon: SiOpenai, color: "#ffffff" },
  perplexity: { icon: SiPerplexity, color: "#1fb8cd" },
  signal: { icon: SiSignal, color: "#3a76f0" },
  slack: { icon: SiSlack, color: "#e01e5a" },
  telegram: { icon: SiTelegram, color: "#26a5e4" },
  trello: { icon: SiTrello, color: "#0052cc" },
  twitch: { icon: SiTwitch, color: "#9146ff" },
  vercel: { icon: SiVercel, color: "#ffffff" },
  "vercel-ai-gateway": { icon: SiVercel, color: "#ffffff" },
  whatsapp: { icon: SiWhatsapp, color: "#25d366" },
  xai: { icon: SiX, color: "#ffffff" },
  xiaomi: { icon: SiXiaomi, color: "#ff6900" },
  zalo: { icon: SiZalo, color: "#0068ff" },
  zalouser: { icon: SiZalo, color: "#0068ff" },
};
