import type { JourneyDay } from "./types";

export const JOURNEY_DAYS: JourneyDay[] = [
  {
    id: "brief",
    day: 1,
    title: "Give Your Agent A Brief",
    mission: "Give your agent a point of view for the work that matters to you.",
    why: "A first brief is not final. It gives this teammate a starting direction before you ask it to do real work.",
    actionLabel: "Start the brief",
    actionKind: "create-agent",
    prompt: "Help me write your first brief. Ask one question at a time: what work I want help with, what good help looks like, what sources you should trust, and when you should ask before acting.",
    briefFocus: ["Role", "Goal", "Starting direction"],
    completionEvents: ["agent-created", "brief-started"],
    receipt: "Your agent now has a starting direction.",
  },
  {
    id: "sources",
    day: 2,
    title: "Show It What Matters",
    mission: "Show your agent one source it should rely on.",
    why: "Sources turn what you already know into context your agent can use.",
    actionLabel: "Add a source",
    actionKind: "open-files",
    briefFocus: ["Trusted source", "Useful note", "Example work"],
    completionEvents: ["source-added"],
    receipt: "Your agent now has something real to work from.",
  },
  {
    id: "rules",
    day: 3,
    title: "Set The Rules",
    mission: "Set where your agent should act, pause, or ask.",
    why: "Clear boundaries help your agent work closer to your judgment.",
    actionLabel: "Set boundaries",
    actionKind: "open-settings",
    prompt: "Help me write a short brief for how you should work with me. Ask before changing billing, deleting files, sending messages, or taking action that could affect other people.",
    promptChips: ["Ask before risky actions", "Use a clear summary first", "Escalate sensitive decisions"],
    briefFocus: ["Boundaries", "Tone", "When to ask"],
    completionEvents: ["rules-confirmed"],
    receipt: "Your agent knows when to pause and ask.",
  },
  {
    id: "real-work",
    day: 4,
    title: "Try Real Work",
    mission: "Try one useful task from today.",
    why: "Real work shows what your agent understands and where it needs refinement.",
    actionLabel: "Draft first task",
    actionKind: "set-chat-prompt",
    prompt: "Use what you know so far and help me with one useful task today. Start by restating the goal, name what information you need, then suggest a safe first step.",
    promptChips: ["Summarize this work", "Find the next step", "Draft a response"],
    briefFocus: ["Real task", "Useful output", "Safe first step"],
    completionEvents: ["chat-sent"],
    receipt: "You've seen how your agent works with your context.",
  },
  {
    id: "understanding",
    day: 5,
    title: "Review What It Understood",
    mission: "Review what your agent got right, missed, or should remember.",
    why: "Small corrections help this teammate become a better extension of how you work.",
    actionLabel: "Review understanding",
    actionKind: "set-chat-prompt",
    prompt: "Review what you understand about how I work so far. List what is clear, what is missing, and what I should correct or add before you help with more work.",
    promptChips: ["What did you understand?", "What are you missing?", "What should you remember?"],
    briefFocus: ["What is clear", "What is missing", "What to remember"],
    completionEvents: ["reviewed-understanding"],
    receipt: "Your agent has a clearer picture of how you work.",
  },
  {
    id: "connections",
    day: 6,
    title: "Connect Where Work Happens",
    mission: "Point your agent toward where your work already lives.",
    why: "Connections help your agent work closer to your real workflow instead of staying in a separate chat.",
    actionLabel: "Choose a connection",
    actionKind: "open-integrations",
    briefFocus: ["Work tools", "Useful places", "Next connection"],
    completionEvents: ["integrations-opened"],
    receipt: "Your agent knows where it can help next.",
  },
  {
    id: "repeatable",
    day: 7,
    title: "Make It Repeatable",
    mission: "Turn one useful task into a repeatable workflow.",
    why: "A repeatable workflow turns useful help into a job your agent can come back to.",
    actionLabel: "Draft a workflow",
    actionKind: "set-chat-prompt",
    prompt: "Turn one useful task from this week into a repeatable workflow. Include the goal, sources to check, rules to follow, when to ask me, and what a good finished result should look like.",
    promptChips: ["Weekly summary", "Inbox triage", "Project check-in"],
    briefFocus: ["Reusable task", "Sources", "Good result"],
    completionEvents: ["workflow-drafted"],
    receipt: "Your agent has a job to come back to.",
  },
];
