import type { JourneyDay } from "./types";

export const JOURNEY_DAYS: JourneyDay[] = [
  {
    id: "brief",
    day: 1,
    title: "Give Your Agent A Brief",
    mission: "Tell your agent what it should help with.",
    why: "A clear brief gives your agent a starting point before you ask it to do real work.",
    actionLabel: "Create or shape agent",
    actionKind: "create-agent",
    prompt: "Help me shape your first brief. Ask me what you should help with, what outcome matters, what sources you should rely on, and when you should ask before acting.",
    briefFocus: ["Role", "Goal", "Starting point"],
    completionEvents: ["agent-created"],
    receipt: "Your agent now has a clear starting point.",
  },
  {
    id: "sources",
    day: 2,
    title: "Show It What Matters",
    mission: "Give your agent one source it should rely on.",
    why: "A source can be a file, note, link, instruction, or example from the work you already know.",
    actionLabel: "Add a source",
    actionKind: "open-files",
    briefFocus: ["Trusted source", "Useful note", "Example work"],
    completionEvents: ["source-added"],
    receipt: "Your agent now has something real to work from.",
  },
  {
    id: "rules",
    day: 3,
    title: "Set The Rules",
    mission: "Decide when your agent should act and when it should ask.",
    why: "Rules make the agent safer to work with because it knows where to be careful.",
    actionLabel: "Add rules",
    actionKind: "open-settings",
    prompt: "Help me write a short brief for how you should work with me. Ask before changing billing, deleting files, sending messages, or taking action that could affect other people.",
    promptChips: ["Ask before risky actions", "Use a clear summary first", "Escalate sensitive decisions"],
    briefFocus: ["Boundaries", "Tone", "When to ask"],
    completionEvents: ["rules-confirmed"],
    receipt: "Your agent knows where to be careful.",
  },
  {
    id: "real-work",
    day: 4,
    title: "Try Real Work",
    mission: "Ask your agent to help with something you actually need today.",
    why: "The fastest way to understand your agent is to give it one useful task from your real work.",
    actionLabel: "Draft a task",
    actionKind: "set-chat-prompt",
    prompt: "Use what you know so far and help me with one useful task today. Start by restating the goal, name what information you need, then suggest a safe first step.",
    promptChips: ["Summarize this work", "Find the next step", "Draft a response"],
    briefFocus: ["Real task", "Useful output", "Safe first step"],
    completionEvents: ["chat-sent"],
    receipt: "You have seen how your agent works with your context.",
  },
  {
    id: "understanding",
    day: 5,
    title: "Review What It Understood",
    mission: "Check what your agent got right, missed, or should remember.",
    why: "Small corrections help the agent build a clearer picture of how you work.",
    actionLabel: "Draft a reflection",
    actionKind: "set-chat-prompt",
    prompt: "Review what you understand about my work so far. List what you know, what you are unsure about, and what I should correct or add before you help with more work.",
    promptChips: ["What did you understand?", "What are you missing?", "What should you remember?"],
    briefFocus: ["What is clear", "What is missing", "What to remember"],
    completionEvents: ["reviewed-understanding"],
    receipt: "Your agent has a clearer picture of how you work.",
  },
  {
    id: "connections",
    day: 6,
    title: "Connect Where Work Happens",
    mission: "Point your agent toward the places your work already lives.",
    why: "Connections help the agent work closer to your existing tools instead of staying in a separate chat.",
    actionLabel: "Choose a connection",
    actionKind: "open-integrations",
    briefFocus: ["Work tools", "Useful places", "Next connection"],
    completionEvents: ["integrations-opened"],
    receipt: "Your agent knows where it can help next.",
  },
  {
    id: "repeatable",
    day: 7,
    title: "Make It Repeatable",
    mission: "Turn one useful task into a repeatable workflow.",
    why: "A repeatable workflow gives your agent a job to come back to instead of starting from scratch each time.",
    actionLabel: "Draft a workflow",
    actionKind: "set-chat-prompt",
    prompt: "Turn one useful task from this week into a repeatable workflow. Include the goal, sources to check, rules to follow, when to ask me, and what a good finished result should look like.",
    promptChips: ["Weekly summary", "Inbox triage", "Project check-in"],
    briefFocus: ["Reusable task", "Sources", "Good result"],
    completionEvents: ["workflow-drafted"],
    receipt: "Your agent is no longer just set up. It has a job to come back to.",
  },
];
