"""Export-surface guard for the hypercli package.

The ts-sdk guards src vs dist exports with dist-exports.test.ts. Here the
package has a single public module, so the guard pins ``hypercli.__all__``
to an explicit list: any new or removed top-level export must be a
deliberate change to this file, and every listed name must actually
resolve to an attribute on the package.
"""
import hypercli

EXPECTED_PUBLIC_SURFACE = frozenset(
    {
        "AGENT_RUNTIME_INACTIVE_STATES",
        "AGENT_TRANSITIONAL_STATES",
        "AGENT_WAIT_RUNNING_FAILURE_STATES",
        "ACPClient",
        "ACPClosedError",
        "ACPError",
        "ACPPromptResult",
        "ACPRequestError",
        "ACPUnavailableError",
        "APIError",
        "Agent",
        "AgentAccessIdentity",
        "AgentCapacity",
        "AgentCorsConfig",
        "AgentLaunchValueMutation",
        "AgentRouteConfig",
        "AgentRoutes",
        "AgentSize",
        "AgentSlot",
        "AgentSlotInventory",
        "ApiKey",
        "AmbiguousDeliveryError",
        "AsyncFiles",
        "AsyncHTTPClient",
        "AuthMe",
        "BaseJob",
        "BuzzAgent",
        "BuzzLaunchConfig",
        "CANONICAL_AGENT_STATES",
        "COMFYUI_IMAGE",
        "ChatEvent",
        "ClaudeCodeAgent",
        "CodexAgent",
        "CodingAgent",
        "ComfyUIJob",
        "DEFAULT_AGENTS_API_BASE_URL",
        "DEFAULT_AGENTS_WS_URL",
        "DEFAULT_AGENT_RUNTIME_SCOPES",
        "DEFAULT_API_URL",
        "DEFAULT_BUZZ_AGENT_IMAGE",
        "DEFAULT_BUZZ_CODING_AGENT_IMAGES",
        "DEFAULT_CODING_AGENT_IMAGES",
        "DEFAULT_CODING_AGENT_SYNC_INCLUDES",
        "DEFAULT_HERMES_AGENT_IMAGE",
        "DEFAULT_HERMES_AGENT_SYNC_EXCLUDE",
        "DEFAULT_HERMES_AGENT_SYNC_ROOT",
        "DEFAULT_OBJECT_INFO",
        "DEFAULT_WS_URL",
        "DEV_AGENTS_API_BASE_URL",
        "DEV_AGENTS_WS_URL",
        "DeploymentEvent",
        "Deployments",
        "DownloadUrl",
        "EnsureWorkspaceResult",
        "ExecResult",
        "File",
        "FlowCatalogItem",
        "GHCR_IMAGES",
        "GPUConfig",
        "GPUMetrics",
        "GPUPricing",
        "GPUType",
        "GatewayChatMessageSummary",
        "GatewayChatToolCall",
        "GatewayClient",
        "GatewayError",
        "GooseAgent",
        "GradioJob",
        "HermesAPIError",
        "HermesAgent",
        "HermesApiClient",
        "HermesCapabilities",
        "HermesDetailedHealth",
        "HermesHealth",
        "HermesMessage",
        "HermesMessageList",
        "HermesModel",
        "HermesModels",
        "HermesRun",
        "HermesSSEEvent",
        "HermesSession",
        "HermesSessionEnvelope",
        "HermesSessionList",
        "HermesSessionModelLock",
        "HyperAgent",
        "HyperAgentBillingInfo",
        "HyperAgentBillingProfileFields",
        "HyperAgentBillingProfileResponse",
        "HyperAgentBillingUser",
        "HyperAgentCanonicalPlanId",
        "HyperAgentCurrentPlan",
        "HyperAgentEntitlement",
        "HyperAgentEntitlements",
        "HyperAgentEntitlementsSummary",
        "HyperAgentKeyUsage",
        "HyperAgentKeyUsageEntry",
        "HyperAgentModel",
        "HyperAgentPayment",
        "HyperAgentPaymentEntitlement",
        "HyperAgentPaymentSubscription",
        "HyperAgentPaymentsResponse",
        "HyperAgentPlan",
        "HyperAgentStripeCheckoutResponse",
        "HyperAgentSubscription",
        "HyperAgentSubscriptionMutationResult",
        "HyperAgentSubscriptionSummary",
        "HyperAgentSubscriptionTrial",
        "HyperAgentTypeCatalog",
        "HyperAgentTypePlan",
        "HyperAgentTypePreset",
        "HyperAgentUsageHistory",
        "HyperAgentUsageHistoryEntry",
        "HyperAgentUsageSummary",
        "HyperAgentX402CheckoutResponse",
        "HyperCLI",
        "Job",
        "JobListPage",
        "JobMetrics",
        "KimiCodeAgent",
        "KeysAPI",
        "LogStream",
        "Model",
        "ModelsAPI",
        "OpenClawAgent",
        "OpenClawProAgent",
        "OpenCodeAgent",
        "PricingTier",
        "Region",
        "Render",
        "RenderStatus",
        "RetryableACPError",
        "Routine",
        "RoutinesAPI",
        "RuntimeAuthClient",
        "RuntimeAuthMethod",
        "RuntimeAuthStatus",
        "RuntimeIdentity",
        "RuntimeLoginSession",
        "ShellSession",
        "User",
        "UserAPI",
        "VoiceAPI",
        "VoiceChunk",
        "VoiceSession",
        "VoiceStreamError",
        "VoiceTranscriptionSession",
        "Workspace",
        "WorkspaceAccessEntry",
        "WorkspaceAccessSnapshot",
        "WorkspaceAccessVisibility",
        "WorkspaceAgentAssociation",
        "WorkspaceFile",
        "WorkspaceGrant",
        "WorkspaceManifest",
        "WorkspacesAPI",
        "X402Client",
        "X402FlowCreate",
        "X402JobLaunch",
        "X402RenderCreate",
        "apply_graph_modes",
        "apply_params",
        "build_agent_config",
        "build_browser_desktop_url",
        "build_hermes_agent_routes",
        "build_openclaw_memory_index_env",
        "build_openclaw_routes",
        "build_openclaw_workspaces_sync_env",
        "configure",
        "expand_subgraphs",
        "extract_gateway_chat_media_urls",
        "extract_gateway_chat_thinking",
        "extract_gateway_chat_tool_calls",
        "fetch_logs",
        "find_by_hostname",
        "find_by_id",
        "find_by_ip",
        "find_job",
        "find_node",
        "find_nodes",
        "get_agent_api_key",
        "get_agents_api_base_url",
        "get_agents_ws_url",
        "get_api_key",
        "get_api_url",
        "get_job_tags",
        "get_ws_url",
        "graph_to_api",
        "is_agent_runtime_inactive_state",
        "is_agent_transitional_state",
        "issue_api_key_from_jwt",
        "job_has_tags",
        "load_template",
        "normalize_gateway_chat_message",
        "normalize_job_tags",
        "parse_hyper_agent_plan_id",
        "shell_connect",
        "stream_logs",
    }
)


def test_public_surface_matches_explicit_list():
    actual = set(hypercli.__all__)
    added = sorted(actual - EXPECTED_PUBLIC_SURFACE)
    removed = sorted(EXPECTED_PUBLIC_SURFACE - actual)
    assert not added and not removed, (
        "Public SDK surface drifted; update EXPECTED_PUBLIC_SURFACE deliberately. "
        f"Added: {added} Removed: {removed}"
    )


def test_public_surface_has_no_duplicates():
    assert len(hypercli.__all__) == len(set(hypercli.__all__))


def test_public_surface_names_resolve():
    missing = [name for name in hypercli.__all__ if not hasattr(hypercli, name)]
    assert missing == []
